### ISSUE TITLE
NullPointerException when exporting DDL

### ISSUE THREAD

**Issue by yasuyuki** [roundrop/ermasterr#1]
I met NullPointerException when exporting DDL from existing diagram.

statcktrace

> java.lang.NullPointerException
>     at java.lang.String.compareTo(String.java:1155)
>     at org.insightech.er.editor.model.diagram_contents.element.connection.Relation.compareTo(Relation.java:397)
>     at org.insightech.er.editor.model.diagram_contents.element.connection.ConnectionElement.compareTo(ConnectionElement.java:1)
>     at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
>     at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
>     at java.util.Arrays.sort(Arrays.java:1312)
>     at java.util.Arrays.sort(Arrays.java:1506)
>     at java.util.ArrayList.sort(ArrayList.java:1454)
>     at java.util.Collections.sort(Collections.java:141)
>     at org.insightech.er.editor.model.diagram_contents.element.node.table.TableSet.sort(TableSet.java:28)
>     at org.insightech.er.editor.model.diagram_contents.element.node.NodeSet.sort(NodeSet.java:42)
>     at org.insightech.er.editor.model.diagram_contents.DiagramContents.sort(DiagramContents.java:63)
>     at org.insightech.er.editor.model.dbexport.AbstractExportManager.init(AbstractExportManager.java:28)
>     at org.insightech.er.editor.view.dialog.dbexport.AbstractExportDialog.perfomeOK(AbstractExportDialog.java:130)
>     at org.insightech.er.editor.view.dialog.dbexport.ExportToDDLDialog.perfomeOK(ExportToDDLDialog.java:415)
>     at org.insightech.er.common.dialog.AbstractDialog.buttonPressed(AbstractDialog.java:224)
>     at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:618)
>     at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
>     at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
>     at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4248)
>     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
>     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
>     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
>     at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
>     at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
>     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
>     at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
>     at org.eclipse.jface.window.Window.open(Window.java:794)
>     at org.insightech.er.editor.view.action.dbexport.AbstractExportWithDialogAction.execute(AbstractExportWithDialogAction.java:27)
>     at org.insightech.er.editor.view.action.AbstractBaseAction.runWithEvent(AbstractBaseAction.java:71)
>     at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
>     at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
>     at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
>     at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4248)
>     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
>     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
>     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
>     at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
>     at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
>     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
>     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
>     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
>     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
>     at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
>     at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
>     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
>     at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
>     at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
>     at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
>     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
>     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
>     at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

It seems 927be93e2f3b0bc74fbfa5091bd076386fe02987 fix is incomplete. If name1 != null and name2 == null, then NullPointerException is thrown.

**Comment by roundrop** [comment]
Thanks for your report.
Fixed and made jar of version 1.1.4. Could you try?

**Comment by yasuyuki** [comment]
It works. thank you.
