### ISSUE TITLE
NullPointerException when exporting DDL

### ISSUE THREAD

**Issue by yasuyuki** [roundrop/ermasterr#2]
I met NullPointerException when exporting DDL from existing diagram.

statcktrace

> java.lang.NullPointerException
>     at org.insightech.er.editor.model.dbexport.ddl.DDLCreator.getUniqueKeyDDL(DDLCreator.java:602)
>     at org.insightech.er.editor.model.dbexport.ddl.DDLCreator.getDDL(DDLCreator.java:522)
>     at org.insightech.er.editor.model.dbexport.ddl.DDLCreator.getCreateTables(DDLCreator.java:314)
>     at org.insightech.er.editor.model.dbexport.ddl.DDLCreator.getCreateDDL(DDLCreator.java:242)
>     at org.insightech.er.editor.model.dbexport.ddl.ExportToDDLManager.doProcess(ExportToDDLManager.java:52)
>     at org.insightech.er.editor.model.dbexport.AbstractExportManager.run(AbstractExportManager.java:41)
>     at org.insightech.er.editor.model.dbexport.ExportManagerRunner.run(ExportManagerRunner.java:20)
>     at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

This stacktrace means local variable "column" is null. Some column deletion action may not delete complex unique key collectly.

**Comment by roundrop** [comment]
I cannot reproduce...
Could you tell me simple steps to reproduce?

**Comment by roundrop** [comment]
Could you try re-save then export DDL?

**Comment by yasuyuki** [comment]
Re-save doesn't cause any effects.
I tried to create small reproducible file, but it failed.

I can try debugging with eclipse debug mode and debug build plug-in.
Please see below.
http://uchanote.blogspot.jp/2012/12/eclipse.html
http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Frunning_eclipse.htm

Can you make debug build plugin?

**Comment by roundrop** [comment]
I can debug the plug-in.
I want to get reproducible .erm file.
Could you give me?

**Comment by yasuyuki** [comment]
My .erm is confidential.
So I tried to debug plugin and found reproducing way.
1. Create two new tables with single integer primary key. They're named as A and B
2. Add two columns to B. They're named as a and b.
3. Add relation B.b refers to A.primary_key with "Relation with existing column"
4. Make B.a and B.b as complex unique key
5. Delete table A with referring column
6. Save diagram and close it
7. Reopen diagram
8. Export DDL

**Comment by roundrop** [comment]
Thanks so much for the reproducing way!
I updated jar file now. Could you try it?

**Comment by yasuyuki** [comment]
It works. thank you.
