### ISSUE TITLE
NullPointerException when selecting "Show referred tables"

### ISSUE THREAD

**Issue by yasuyuki** [roundrop/ermasterr#3]
I met NullPointerException.
1. Create new diagram
2. Right click > category > Show refered tables

stacktrace

> java.lang.NullPointerException
>     at org.insightech.er.editor.controller.command.category.ChangeShowReferredTablesCommand.refreshReferredNodeElementList(ChangeShowReferredTablesCommand.java:48)
>     at org.insightech.er.editor.controller.command.category.ChangeShowReferredTablesCommand.doExecute(ChangeShowReferredTablesCommand.java:35)
>     at org.insightech.er.editor.controller.command.AbstractCommand.execute(AbstractCommand.java:14)
>     at org.eclipse.gef.commands.CommandStack.execute(CommandStack.java:228)
>     at org.insightech.er.editor.view.action.AbstractBaseAction.execute(AbstractBaseAction.java:81)
>     at org.insightech.er.editor.view.action.category.ChangeShowReferredTablesAction.execute(ChangeShowReferredTablesAction.java:29)
>     at org.insightech.er.editor.view.action.AbstractBaseAction.runWithEvent(AbstractBaseAction.java:71)
>     at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
>     at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
>     at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
>     at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4248)
>     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
>     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
>     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
>     at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
>     at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
>     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
>     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
>     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
>     at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
>     at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
>     at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
>     at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
>     at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
>     at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
>     at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
>     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
>     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
>     at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by roundrop** [comment]
ermasterr is disabling category concept found in original version of ERMaster for speeding up.
I'm going to hide the 'Category' popup menu.
Thanks,

**Comment by roundrop** [comment]
Thanks
