### ISSUE TITLE
Duplicate Oracle sequence and unable to delete it

### ISSUE THREAD

**Issue by yasuyuki** [roundrop/ermasterr#4]
Oracle doesn't support auto number, so ermasterr adds sequence and trigger.
But they doesn't refer table renaming.
1. Create diagram using Oracle database
2. Create table
3. Add column id as number, auto increment, primary key
4. Close table edit dialog
5. Click ok to confirming dialog
6. Open table edit dialog
7. Rename table
8. Close table edit dialog
9. Click ok to confirming dialog
10. Export DDL

Exported DDL contains two sequence and triggers which are named from original and renamed table names, and there's no way to delete them.

**Comment by roundrop** [comment]
Thanks for the steps to reproduce.
I've fixed and create jar 1.1.8 .
Could you try?

**Comment by yasuyuki** [comment]
It works.
Thank you.
