### ISSUE TITLE
ermasterr提供のantタスクを実行するとNoSuchMethodErrorが発生する

### ISSUE THREAD

**Issue by ghost** [roundrop/ermasterr#5]
## Title

ermasterr提供のantタスクを実行するとNoSuchMethodErrorが発生する
## Comment

初めてissueを書きますので不得手な部分がありますがご了承ください。
### 実行環境

Eclipse Version: Mars.2 Release (4.5.2)
### 再現手順

> 1. ermファイルを作成する ( sampleのermファイル添付あり
> 2. antからermasterが提供しているタスクを実行する  ( sampleのbuild.xml,build.properties 添付あり
> 3. 実行すると、実行時エラーが発生。下記を出力
## StackTrace

Buildfile: /Users/mac-user/devel/project/ermasterr/helloMavenErmasterr/src/main/java/hogehoge/helloMavenErmasterr/ant/build.xml

ddl:
[ermaster.ddl] <ermaster.ddl> have these attributes. (the attribute with '*' must be set.) 
[ermaster.ddl]     \* diagramFile - The path of the input .erm file.
[ermaster.ddl]     \* outputFile  - The path of the output ddl file.
[ermaster.ddl]       encoding    - The encoding of the output ddl file.
[ermaster.ddl] Base Location : /Users/mac-user/devel/project/ermasterr/helloMavenErmasterr/src/main/java/hogehoge/helloMavenErmasterr/ant/build.xml
[ermaster.ddl] Load the diagram file : /Users/mac-user/devel/project/ermasterr/helloMavenErmasterr/src/main/java/hogehoge/helloMavenErmasterr/ant/ddl-export-test.erm
[ermaster.ddl] java.lang.NoSuchMethodError: org.insightech.er.editor.persistent.Persistent.load(Ljava/io/InputStream;)Lorg/insightech/er/editor/model/ERDiagram;
[ermaster.ddl]  at org.insightech.er.ant_task.ERMasterAntTaskBase.execute(ERMasterAntTaskBase.java:70)
[ermaster.ddl]  at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[ermaster.ddl]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ermaster.ddl]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ermaster.ddl]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ermaster.ddl]  at java.lang.reflect.Method.invoke(Method.java:497)
[ermaster.ddl]  at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[ermaster.ddl]  at org.apache.tools.ant.Task.perform(Task.java:348)
[ermaster.ddl]  at org.apache.tools.ant.Target.execute(Target.java:435)
[ermaster.ddl]  at org.apache.tools.ant.Target.performTasks(Target.java:456)
[ermaster.ddl]  at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
[ermaster.ddl]  at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
[ermaster.ddl]  at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[ermaster.ddl]  at org.eclipse.ant.internal.core.ant.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:36)
[ermaster.ddl]  at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
[ermaster.ddl]  at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:705)
[ermaster.ddl]  at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:527)
[ermaster.ddl]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ermaster.ddl]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ermaster.ddl]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ermaster.ddl]  at java.lang.reflect.Method.invoke(Method.java:497)
[ermaster.ddl]  at org.eclipse.ant.core.AntRunner.run(AntRunner.java:371)
[ermaster.ddl]  at org.eclipse.ant.internal.launching.launchConfigurations.AntLaunchDelegate$1.run(AntLaunchDelegate.java:269)
[ermaster.ddl]  at java.lang.Thread.run(Thread.java:745)

BUILD FAILED
/Users/mac-user/devel/project/ermasterr/helloMavenErmasterr/src/main/java/hogehoge/helloMavenErmasterr/ant/build.xml:5: java.lang.NoSuchMethodError: org.insightech.er.editor.persistent.Persistent.load(Ljava/io/InputStream;)Lorg/insightech/er/editor/model/ERDiagram;

Total time: 276 milliseconds
### 原因

該当箇所のメソッドシグニチャは下記となります。

package org.insightech.er.editor.persistent.Persistent

public abstract ERDiagram load(InputStream paramInputStream, File paramFile)
    throws Exception;
}
### 発生の起因について

https://github.com/roundrop/ermasterr/commit/b6e1c89fbee35cf2b34c69ced11aad78d8696bcf#diff-8bd0df1b31d7a984a24ca5aec02c72f0

**Comment by ghost** [comment]
再現用のファイルについて添付します
[ant.zip](https://github.com/roundrop/ermasterr/files/491473/ant.zip)

**Comment by roundrop** [comment]
I've fixed then create jar file 1.1.9 .
Please try it.

Thanks,
