### ISSUE TITLE
Error importing Database Postgresql 9.6.2.

### ISSUE THREAD

**Issue by elidorio** [roundrop/ermasterr#8]
Hello,

I'm testing ERmaster (org.insightech.er _ 1.1.11) on Windows 10 and presented the below error when importing a Database Postgresql 9.6.2.
![eermasterr](https://cloud.githubusercontent.com/assets/2966579/22868274/25f07efc-f17b-11e6-8614-fba0c18f9476.png)

**Comment by roundrop** [comment]
Could you show me the reproducible DDL?
