### ISSUE TITLE
Problem importing column with the char in PostgreSQL

### ISSUE THREAD

**Issue by elidorio** [roundrop/ermasterr#9]
Hello,
Problem importing column with the char in PostgreSQL
For example
Correct would be like this:
fg_tipo_lcto char (1) NOT NULL, - Showing as char (n) in ERMaster
This matter wrong:
fg_tipo_lcto char NOT NULL,
ERmaster in the char (n) this appearing as char.
greetings;
Edson

https://sourceforge.net/p/ermaster/bugs/117/

**Comment by elidorio** [comment]
This test here I did in linux?

**Comment by roundrop** [comment]
no problem because 'char' is equivalent to 'char(1)'.

> The notations varchar(n) and char(n) are aliases for character varying(n) and character(n), respectively. character without length specifier is equivalent to character(1). If character varying is used without length specifier, the type accepts strings of any size. The latter is a PostgreSQL extension.

https://www.postgresql.org/docs/9.6/static/datatype-character.html
